"""Add progress and metrics to TestRun

Revision ID: 1d284c23e131
Revises: 20260603_initial
Create Date: 2026-06-04 16:15:00.575556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d284c23e131'
down_revision: Union[str, None] = '20260603_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_runs', sa.Column('progress', sa.Integer(), nullable=True))
    op.add_column('test_runs', sa.Column('metrics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_runs', 'metrics')
    op.drop_column('test_runs', 'progress')
    # ### end Alembic commands ###
